/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppBoardRouteImport } from './routes/app.board'
import { Route as AppFilesRouteImport } from './routes/app.files'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppTeamRouteImport } from './routes/app.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/board': typeof AppBoardRoute
  '/app/files': typeof AppFilesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/board': typeof AppBoardRoute
  '/app/files': typeof AppFilesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/board': typeof AppBoardRoute
  '/app/files': typeof AppFilesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/analytics'
    | '/app/board'
    | '/app/files'
    | '/app/projects'
    | '/app/team'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/analytics'
    | '/app/board'
    | '/app/files'
    | '/app/projects'
    | '/app/team'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/analytics'
    | '/app/board'
    | '/app/files'
    | '/app/projects'
    | '/app/team'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBoardRoute: typeof AppBoardRoute
  AppFilesRoute: typeof AppFilesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBoardRoute: AppBoardRoute,
  AppFilesRoute: AppFilesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
